numtimes=list()
for i in range(1,12):
    start=time.time()
    n=int(input("Enter The no of Elements"))
    numtimes=append(n)
    for x in range(n):
        number=np.random.randint(10,99)
        arr.append(number)
    print("list before sorting",x+1,"Elements")
    print(arr)
    bubblesort (arr)
    end=time.time()
    times.append(end-Start)
print("list after bubblesort of",x+,"Elements")
print(arr)
print(numtimes)
print(times)
plt.xlable("list length")
plt.ylable("time complexity")
plt.plot(numtimes,times,lable="bubble")
plt.grid()
plt .leged()
plt.show()